; [env:nrf52840_development_board]
; platform = nordicnrf52
; board = adafruit_feather_nrf52840
; framework = arduino
; lib_deps = 
;     62
; monitor_speed = 115200

[env:nrf52840_development_board]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
lib_deps = 62
monitor_speed = 115200
; ДОБАВИ ТЕЗИ РЕДОВЕ:
build_flags = 
    -DNRF52840_XXAA
    -DUSE_TINYUSB